### ISSUE TITLE
Investigate if XP from non-editor panels can be avoided

### ISSUE THREAD

**Issue by runebaas** [code-stats/code-stats-intellij#5] opened 2017-03-13 10:56 UTC
I get random plain text xp for some reason. I've already got 2,411 XP but i've never typed something in a plain text file... 
I can't figure out what it causes, it is a bug or is it intellij being strange?

intellij idea 2016.3
osx sierra (doesn't happen on windows)

**Comment by Nicd** [comment] 2017-03-13 10:58
This can be caused by typing into a file that is not recognised by IntelliJ (it will report plain text then). If you want to join our Gitter channel https://gitter.im/code-stats/Lobby it's easier to debug further.

**Comment by runebaas** [comment] 2017-03-13 11:03
According to the website i earned a 100xp plain text this morning even though i've only been typing in a javascript file which was reported correctly...

**Comment by Nicd** [comment] 2017-03-13 11:12
Have you been using search a lot? IntelliJ counts typing into the search box as plaintext (or RegEx if you have the regex ticked). Maybe there are other such builtin panels it counts too.

**Comment by runebaas** [comment] 2017-03-13 12:13
Yes, i do search search and goto a lot as well as the git gui sometimes. I tested it and it was that which was counted.

That means that is is not a bug after all... Thanks for clarifying

**Comment by Nicd** [comment] 2017-03-13 12:49
Maybe that isn't very intuitive, but I don't know how to detect when the typed panel is an editor and when it is not. I hope it's not a big issue for you. It should matter less when I get "last X days" style statistics implemented.

**Comment by runebaas** [comment] 2017-03-13 12:57
How about not counting plain text at all? i mean, Intellij recognizes almost every filetype anyways and if not, there is some plugin for it which will.

**Comment by Nicd** [comment] 2017-03-13 13:10
Plain text should be counted if you are writing plain text and that's a feature that I want to have. So it should detect non-code panels if possible. One option is to wontfix it since the new statistics should make it less of an issue.

**Comment by runebaas** [comment] 2017-03-13 13:19
In that case, just do a won't fix. I'm not familiar with the Intellij plugin sdk so i can't really talk here

**Comment by Nicd** [comment] 2017-11-19 14:39
Please follow this issue on GitLab: https://gitlab.com/code-stats/code-stats-intellij/issues/5

**Closed by Nicd** 2017-11-19 14:39 UTC
Labels: bug
